"""M1 · Preprocessing regression test.

Checks the preprocessed CSVs against ESA's own shipped reference numbers and the raw
Zenodo data — independent of the detector and of the 0.949 result. If preprocessing
ever breaks, one of these invariants fails.

Run: pytest tests/test_m1_preprocessing.py -v
Requires: data/preprocessed_subset/... generated by src/m1_detection/preprocessing.py.
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
import config  # noqa: E402

# ESA's shipped datasets.csv reference (esa-adb/data/preprocessed/datasets.csv), 104-dim run.
REF_GRID_LENGTH = {"1_months": 148801, "5_months": 729601, "10_months": 1464001, "21_months": 3067201}
REF_MAX_ANOMALY = {"1_months": 540, "5_months": 8049, "10_months": 8049, "21_months": 93029}

pytestmark = pytest.mark.skipif(
    not config.PREP_DIR.exists(),
    reason="preprocessed data missing; run src/m1_detection/preprocessing.py first",
)


def _meta(split: str) -> dict:
    return json.load(open(config.PREP_DIR / f"{split}.metadata.json"))[0]


@pytest.mark.parametrize("split,expected", REF_GRID_LENGTH.items())
def test_grid_length_matches_esa_reference(split, expected):
    """Time-grid length per split == ESA shipped reference (channel-independent)."""
    assert _meta(split)["length"] == expected


@pytest.mark.parametrize("split,expected", REF_MAX_ANOMALY.items())
def test_max_anomaly_length_matches_esa_reference(split, expected):
    """Longest anomaly (in 18s samples) == ESA shipped reference."""
    m = _meta(split)
    assert max(v["max"] for v in m["anomaly_length"].values()) == expected


def test_18s_spacing():
    s = pd.read_csv(config.TEST_CSV, usecols=["timestamp"], nrows=200, parse_dates=["timestamp"])
    diffs = s["timestamp"].diff().dropna().dt.total_seconds().unique()
    assert list(diffs) == [18.0]


def test_train_test_split_boundary():
    tr_last = pd.read_csv(config.TRAIN_CSV, usecols=["timestamp"]).iloc[-1, 0]
    te_first = pd.read_csv(config.TEST_CSV, usecols=["timestamp"]).iloc[0, 0]
    # ESA design: train index <= split, test index > split; resample floor/ceil -> both touch it.
    assert tr_last <= "2001-10-01 00:00:00" and te_first >= "2001-10-01 00:00:00"


def test_is_anomaly_domain():
    cols = pd.read_csv(config.TEST_CSV, nrows=0).columns
    acol = next(c for c in cols if c.startswith("is_anomaly_channel"))
    vals = set(pd.read_csv(config.TEST_CSV, usecols=[acol])[acol].unique())
    assert vals <= {0, 1, 2}


def test_value_matches_raw_zero_order_hold():
    """First test rows of channel_18 == raw value after the split (ESA iloc[0] init + ffill)."""
    raw = pd.read_pickle(config.REPO / "data" / "ESA-Mission2" / "channels" / "channel_18.zip")
    raw = raw.rename(columns={"channel_18": "value"})
    raw.index = pd.to_datetime(raw.index)
    split = pd.Timestamp("2001-10-01 00:00:00")
    samp = pd.read_csv(config.TEST_CSV, usecols=["timestamp", "channel_18"], nrows=5, parse_dates=["timestamp"])
    # row 0 = first raw value strictly after the split; rows 1+ = ffill within test range.
    assert np.isclose(samp["channel_18"].iloc[0], raw[raw.index > split]["value"].iloc[0], atol=1e-5)
    for _, r in samp.iloc[1:].iterrows():
        assert np.isclose(r["channel_18"], raw.loc[:r["timestamp"], "value"].iloc[-1], atol=1e-6)
